name: coolmovies
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <4.0.0"


dependencies:
  flutter:
    sdk: flutter
  graphql_flutter: ^5.1.2
  cupertino_icons: ^1.0.2
  graphql: ^5.1.3
  get_it: 7.6.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  graphql_codegen: ^0.12.2
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8

flutter:

  uses-material-design: true

